name: Auto V2Ray Update

on:
  schedule:
    - cron: '0 */4 * * *' # Runs every 4 hours
  workflow_dispatch:      # Manual Run Button

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows saving files
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install Dependencies
        run: pip install -r requirements.txt
        
      - name: Run Bot Script
        run: python main.py
        
      - name: Commit and Push
        run: |
          git config --global user.name "V2Ray Bot"
          git config --global user.email "bot@github.com"
          git add vless.txt sub.txt
          git diff --quiet && git diff --staged --quiet || (git commit -m "ðŸš€ Auto-update working servers" && git push)
